### PR TITLE
[failing] add test for aeson compliance of sum-record-types

### PR DESCRIPTION
**Pull request by soenkehahn**
Don't merge, this PR just adds a failing test-case.

`aeson` doesn't bundle up the fields in a `contents` field in case of sum-types that are records.

### CODE REVIEW

**Comment by eskimor** [comment]
Thank you - I'll check!

**Comment by eskimor** [comment]
I can confirm that aeson indeed behaves this way, including a blow up if the record contains a tag element already:

``` haskell
data Test1 = Test1 { foo :: String, bar :: Int } 
     | Test2 { hi :: String, there :: Int, tag :: String } deriving (Generic,Show)
instance ToJSON Test1
instance FromJSON Test1

-- We get a Nothing - obviously, as there is no constructor named `Huhu`:
*Servant.Subscriber.Types Data.Aeson> decode $ encode $ Test2 { hi = "haha", there = 9, tag = "Huhu" } :: Maybe Test1 
Nothing

-- It works if the tag value happens to be the constructor name:
*Servant.Subscriber.Types Data.Aeson> decode $ encode $ Test2 { hi = "haha", there = 9, tag = "Test2" } :: Maybe Test1
Just (Test2 {hi = "haha", there = 9, tag = "Test2"})

-- Encoded output:
encode $ Test2 { hi = "haha", there = 9, tag = "Huhu" }
"{\"tag\":\"Huhu\",\"there\":9,\"hi\":\"haha\"}"
```

I don't think that this is ideal, but that is not our problem to solve - we have to be compatible - so I'll fix this library to work the same way.

**Comment by eskimor** [comment]
This behavior is actually pretty well [documented](http://hackage.haskell.org/package/aeson-1.0.1.0/docs/Data-Aeson-Types.html#t:SumEncoding) - _dumdididum_. Thank you for bringing this to my attention.

**Comment by soenkehahn** [comment]
It is documented, but I think it's very counter-intuitive. I at least was very surprised.

**Pull request merged**
