### PR TITLE
Upgrade to PureScript 0.10.2

### PR DESCRIPTION
**Pull request by parsonsmatt**
This PR updates the dependencies and libraries to work with PureScript 0.10.2 compiler.

I've verified that tests run and pass, though you may want to wait on [this PR](https://github.com/zudov/purescript-strongcheck-generics/pull/6) to be released before merging.

### CODE REVIEW

**Comment by eskimor** [comment]
Thank you! Yeah - if it is not a problem for you, let's wait until strongcheck-generics are merged.

**Comment by eskimor** [comment]
ping @parsonsmatt, I think strongcheck got merged?

**Comment by parsonsmatt** [comment]
It did, but there's some issue with [recursive signatures](https://github.com/zudov/purescript-strongcheck-generics/issues/5). It doesn't affect the tests for this repo, IIRC.

**Comment by eskimor** [comment]
I see. Thanks!

**Comment by legrostdg** [comment]
Can this be merged, now that the failing test has been commented? https://github.com/zudov/purescript-strongcheck-generics/issues/5

**Comment by eskimor** [comment]
done, but I haven't tested, I currently have no purescript available.

**Comment by legrostdg** [comment]
Maybe the dependencies should be updated, at least `purescript-strongcheck-generics` should be set to `^0.5.1`

**Comment by legrostdg** [comment]
Already done, OK :)

**Pull request merged**
